/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stm32f407xx.h>

volatile uint32_t count = 0;

void EXTI0_IRQHandler_Custom(void);

void delay(uint32_t t)
{
	for(int i=0;i<t;i++)
	{
		for(int j=0;j<1000;j++)
		{

		}
	}
}

void GPIO_Init(void)
{
	// Enable clock for port A and port D
	RCC->AHB1ENR |= (1 << 0) | (1 << 3);

	// Mode: Set PA0 as Input
	GPIOA->MODER &= ~(3U << 0);

	// No pull-up, pull-down(exist a resistor on board)
	GPIOA->PUPDR &= ~(3u<<0);

	// Mode: Set PD12 as output
	GPIOD->MODER &= ~(3U << 24);
	GPIOD->MODER |= (1U << 24);

	// Output type: push-pull
	GPIOD->OTYPER &= ~(1 << 12);

	// Speed: medium
	GPIOD->OSPEEDR &= ~(3 << 24);
	GPIOD->OSPEEDR |= (1 << 24);
}

void EXTI_Init(void)
{
	/*
	 * SYSCFG external interrupt configuration
	 * Configure the mask bits of the 23 interrupt lines (EXTI_IMR)
	 * Configure the Trigger selection bits of the interrupt lines (EXTI_RTSR and EXTI_FTSR)
	 * Configure the enable and mask bits that control the NVIC IRQ channel
	 *
	 * */

	// Select source for line 0 as PA port
	SYSCFG->EXTICR[0] &= ~ SYSCFG_EXTICR1_EXTI0_Msk;

	// Set interrupt mask for line 0(PA0)
	EXTI->IMR |= 1 << EXTI_IMR_MR0_Pos;

	// Falling edge interrupt
	EXTI->FTSR |= 1 << EXTI_FTSR_TR0_Pos;

	// NVIC
	__NVIC_EnableIRQ(EXTI0_IRQn);
}

void move_vector_table(void)
{
	/* Modify linker file to vector table won't overwrite to variable
	 * VTTBL    (xrw)    : ORIGIN = 0x20000000,   LENGTH = 1K
	 * Copy vector table to RAM
	 * Change offset for vector table in cortex ARM
	 * Modify interrupt handler in vector table
	 * */

	uint8_t *pFLASH = 0;
	uint8_t *pRAM = (uint8_t *)0x20000000;
	uint32_t *PVTOR = (uint32_t *)0x20000000;

	// Copy vector table to RAM
	for(uint32_t i = 0 ; i< 0x184;i++)
	{
		pRAM[i] = pFLASH[i];
	}

	// Change offset for vector table in cortex ARM
	SCB->VTOR = 0x20000000;

	// Modify interrupt handler in vector table
	*(PVTOR + 22) = (uint32_t)EXTI0_IRQHandler_Custom | 1;

}

int main(void)
{
	GPIO_Init();
	EXTI_Init();

	move_vector_table();

	while(1)
	{
		if(count == 1)
		{
			delay(30);
			GPIOD->ODR ^= (1 << 12);
			count = 0;
		}
	}
}

void EXTI0_IRQHandler_Custom(void)
{
	// Clear Pending bit
	EXTI->PR |= 1 << EXTI_PR_PR0_Pos;

	count = 1;
}
