/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stm32f407xx.h>

#define read_button	((GPIOA->IDR & 0x01) >> 0)

void delay(uint32_t t)
{
	for(int i=0;i<t;i++)
	{
		for(int j=0;j<1000;j++)
		{

		}
	}
}

int main(void)
{
	/* 1. Enable clock for port
	 * 2. Mode
	 * 3. pull up or pull down resistor
	 *
	 * */

	// Enable clock for port A and port D
	RCC->AHB1ENR |= (1 << 0) | (1 << 3);

	// Mode: Set PA0 as Input
	GPIOA->MODER &= ~(3U << 0);

	// No pull-up, pull-down(exist a resistor on board)
	GPIOA->PUPDR &= ~(3u<<0);

	// Mode: Set PD12 as output
	GPIOD->MODER &= ~(3U << 24);
	GPIOD->MODER |= (1U << 24);

	// Output type: push-pull
	GPIOD->OTYPER &= ~(1 << 12);

	// Speed: medium
	GPIOD->OSPEEDR &= ~(3 << 24);
	GPIOD->OSPEEDR |= (1 << 24);

	while(1)
	{
		if(read_button == 1)
		{
			delay(30);
			if(read_button == 1)
			{
				GPIOD->ODR ^= (1 << 12);
				while(read_button == 1);
			}
		}
	}
}
