/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stm32f407xx.h>

uint16_t adc_value[3] = {0};

void delay(uint32_t t)
{
	for(int i=0;i<t;i++)
	{
		for(int j=0;j<1000;j++)
		{

		}
	}
}

void GPIO_Init(void)
{
	// Enable clock for port A, port C and port D
	RCC->AHB1ENR |= (1 << 0) | (1 << 2) | (1 << 3);

	// Mode: Set PD12, PD13, PD14 and PD15 as output
	GPIOD->MODER &= ~((3U << GPIO_MODER_MODER12_Pos)| (3U << GPIO_MODER_MODER13_Pos) | (3U << GPIO_MODER_MODER14_Pos) | (3U << GPIO_MODER_MODER15_Pos));
	GPIOD->MODER |= (1U << GPIO_MODER_MODER12_Pos)| (1U << GPIO_MODER_MODER13_Pos) | (1U << GPIO_MODER_MODER14_Pos) | (1U << GPIO_MODER_MODER15_Pos);

	// Output type: push-pull
	GPIOD->OTYPER &= ~(0b1111 << 12);

	// Speed: medium
	GPIOD->OSPEEDR &= ~(0b11111111 << 24);
	GPIOD->OSPEEDR |= (0b01010101 << 24);

	// Mode: Set PC0, PC1, PC2 as Analog mode
	GPIOC->MODER |= (0x3F << 0);

	// Mode: Set PC11 as Input(external trigger source)
	GPIOC->MODER &= ~(3U << GPIO_MODER_MODE11_Pos);

	// No pull-up, pull-down(exist a resistor on board)
	GPIOC->PUPDR &= ~(3u << GPIO_PUPDR_PUPD11_Pos);

}

void ADC_Init(void)
{
	/* 1. Clock
	 * 2. Conversion mode
	 * 3. Scan Mode
	 * 4. Multiple channel
	 * 5. VRef
	 * 6. Sample time
	 * 7. Resolution
	 * 8. Trigger source
	 * 9. A/D Converter ON / OFF
	 * */

	// 1. Enable Clock
	RCC->APB2ENR |= (1<< RCC_APB2ENR_ADC1EN_Pos);

	// 2. Conversion mode: Single conversion mode
	ADC1->CR2 &= ~ ADC_CR2_CONT_Msk;

	// 3. Scan Mode: Disable
	ADC1->CR1 &= ~(1 << ADC_CR1_SCAN_Pos);

	// 4. Single channel: PC0(ADC123_IN10)
	ADC1->SQR3 = 10 << ADC_SQR3_SQ1_Pos;

	// Regular channel sequence length: 2 conversions
	ADC1->SQR1 |= 0 << ADC_SQR1_L_Pos;

	// 5. VRef

	// 6. Sample time
	ADC1->SMPR2 |= (7 << 0) | (7 << 3) | (7 << 6);

	// 7. Resolution:  12-bit
	ADC1->CR1 &= ~ ADC_CR1_RES_Msk;

	// 8. Trigger source: EXTI line11
	ADC1->CR2 |= (15 << ADC_CR2_EXTSEL_Pos);

	// External trigger enable: Trigger detection on the falling edge
	ADC1->CR2 |= (2 << ADC_CR2_EXTEN_Pos);

	// 9. Enable ADC
	ADC1->CR2 |= (1 << ADC_CR2_ADON_Pos);

}

void ADC_External_Trigger(void)
{
	// Enable clock for SYSCFG peripheral
	RCC->APB2ENR |= (1<< RCC_APB2ENR_SYSCFGEN_Pos);

	// Select source for line 11 as PC port
	SYSCFG->EXTICR[2] |= 2 << SYSCFG_EXTICR3_EXTI11_Pos;

	// Set event mask for line 11(PC11)
	EXTI->EMR |= 1 << EXTI_EMR_MR11_Pos;

	// Falling edge interrupt
	EXTI->FTSR |= 1 << EXTI_FTSR_TR11_Pos;

}

int main(void)
{
	GPIO_Init();
	ADC_External_Trigger();
	ADC_Init();

	while(1)
	{
		//  wait for sequence of conversions complete
		while( ! ((ADC1->SR >> ADC_SR_EOC_Pos) & 0x01));
		adc_value[0] = ADC1->DR;

		if(adc_value[0] > 1000)
		{
			GPIOD->ODR |= 1 << 12;
		}
		else
		{
			GPIOD->ODR &= ~(1 << 12);
		}

		delay(500);
	}
}
