/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stm32f407xx.h>

uint16_t adc_value[3] = {0};

void delay(uint32_t t)
{
	for(int i=0;i<t;i++)
	{
		for(int j=0;j<1000;j++)
		{

		}
	}
}

void GPIO_Init(void)
{
	// Enable clock for port A, port C and port D
	RCC->AHB1ENR |= (1 << 0) | (1 << 2) | (1 << 3);

	// Mode: Set PA0 as Input
	GPIOA->MODER &= ~(3U << 0);

	// No pull-up, pull-down(exist a resistor on board)
	GPIOA->PUPDR &= ~(3u<<0);

	// Mode: Set PD12, PD13, PD14 and PD15 as output
	GPIOD->MODER &= ~((3U << GPIO_MODER_MODER12_Pos)| (3U << GPIO_MODER_MODER13_Pos) | (3U << GPIO_MODER_MODER14_Pos) | (3U << GPIO_MODER_MODER15_Pos));
	GPIOD->MODER |= (1U << GPIO_MODER_MODER12_Pos)| (1U << GPIO_MODER_MODER13_Pos) | (1U << GPIO_MODER_MODER14_Pos) | (1U << GPIO_MODER_MODER15_Pos);

	// Output type: push-pull
	GPIOD->OTYPER &= ~(0b1111 << 12);

	// Speed: medium
	GPIOD->OSPEEDR &= ~(0b11111111 << 24);
	GPIOD->OSPEEDR |= (0b01010101 << 24);

	// Mode: Set PC0, PC1, PC2 as Analog mode
	GPIOC->MODER |= (0x3F << 0);

}

void ADC_Init(void)
{
	/* 1. Clock
	 * 2. Conversion mode
	 * 3. Channel
	 * 4. Sample time
	 * 5. Resolution
	 * 6. A/D Converter ON / OFF
	 * */

	// 1. Enable Clock
	RCC->APB2ENR |= (1<< RCC_APB2ENR_ADC1EN_Pos);

	// 2. Conversion mode: Continuous conversion mode
	ADC1->CR2 |= (1 << ADC_CR2_CONT_Pos);

	/* Note that
	 * Injected channels cannot be converted continuously
	 * No scan mode, no  multiple channel
	 * */

	// 3. Channel: PC0(ADC123_IN10)
	ADC1->SQR3 = (10 << ADC_SQR3_SQ1_Pos);

	// 4. Sample time
	ADC1->SMPR2 |= (7 << 0);

	// 5. Resolution:  12-bit
	ADC1->CR1 &= ~ ADC_CR1_RES_Msk;

	// 6. Enable ADC
	ADC1->CR2 |= (1 << ADC_CR2_ADON_Pos);

}

void ADC_Start_Conversion(void)
{
	// Software trigger: Start conversion of regular channels
	ADC1->CR2 |= (1 << ADC_CR2_SWSTART_Pos);

}

int main(void)
{
	GPIO_Init();
	ADC_Init();

	// start command use only once
	ADC_Start_Conversion();

	while(1)
	{
		//  wait for sequence of conversions complete
		while( ! ((ADC1->SR >> ADC_SR_EOC_Pos) & 0x01));
		adc_value[0] = ADC1->DR;

		if(adc_value[0] > 1000)
		{
			GPIOD->ODR |= 1 << 12;
		}
		else
		{
			GPIOD->ODR &= ~(1 << 12);
		}

		delay(500);
	}
}
