/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stm32f407xx.h>

void delay(uint32_t t)
{
	for(int i=0;i<t;i++)
	{
		for(int j=0;j<1000;j++)
		{

		}
	}
}

int main(void)
{
	/* 1. Enable clock for port
	 * 2. Mode
	 * 3. Output type
	 * 4. Output speed
	 * 5. set or clear pin
	 * */

	// Enable clock for port D
	RCC->AHB1ENR |= 1 << RCC_AHB1ENR_GPIODEN_Pos;

	// Mode: Set PD12, PD13, PD14 and PD15 as output
	GPIOD->MODER &= ~((3U << GPIO_MODER_MODER12_Pos)| (3U << GPIO_MODER_MODER13_Pos) | (3U << GPIO_MODER_MODER14_Pos) | (3U << GPIO_MODER_MODER15_Pos));
	GPIOD->MODER |= (1U << GPIO_MODER_MODER12_Pos)| (1U << GPIO_MODER_MODER13_Pos) | (1U << GPIO_MODER_MODER14_Pos) | (1U << GPIO_MODER_MODER15_Pos);

	// Output type: push-pull
	GPIOD->OTYPER &= ~(0b1111 << 12);

	// Speed: medium
	GPIOD->OSPEEDR &= ~(0b11111111 << 24);
	GPIOD->OSPEEDR |= (0b01010101 << 24);

	while(1)
	{
		// Set 4 GPIOs to high
		GPIOD->BSRR |= (0b1111) << 12;
		delay(100);

		// Set 4 GPIOs to low
		GPIOD->BSRR |= (0b1111) << 28;
		delay(100);
	}
}
