/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stm32f407xx.h>

void delay(uint32_t t)
{
	for(int i=0;i<t;i++)
	{
		for(int j=0;j<1000;j++)
		{

		}
	}
}

int main(void)
{
	/* Enable clock for port D */
	RCC->AHB1ENR |= 1<<3;

	/* Set output for Pin PD12, 13, 14, 15 */
	GPIOD->MODER |= (1U<<24)| (1U<<26) | (1U<<28) | (1U<<30);

	while(1)
	{
		GPIOD->BSRR |= (0b1111)<<12;
		delay(100);
		GPIOD->BSRR |= (0b1111)<<28;
		delay(100);
	}
}
