/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stm32f407xx.h>

void delay(uint32_t t)
{
	for(int i=0;i<t;i++)
	{
		for(int j=0;j<1000;j++)
		{

		}
	}
}

int main(void)
{
	volatile uint32_t lock_status;

	/* LOCK key write sequence:
	 * 1. WR LCKR[16] = ‘1’ + LCKR[15:0]
	 * 2. WR LCKR[16] = ‘0’ + LCKR[15:0]
	 * 3. WR LCKR[16] = ‘1’ + LCKR[15:0]
	 * 4. RD LCKR
	 * 5. RD LCKR[16] = ‘1’
	 * */

	// Enable clock for port D
	RCC->AHB1ENR |= 1 << 3;

	// Mode: Set PD12 as output
	GPIOD->MODER &= ~(3U << 24);
	GPIOD->MODER |= (1U << 24);

	// Output type: push-pull
	GPIOD->OTYPER &= ~(1U << 12);

	// Speed: medium
	GPIOD->OSPEEDR &= ~(3U << 24);
	GPIOD->OSPEEDR |= (1U << 24);

	// 1. WR LCKR[16] = ‘1’ + LCKR[15:0]
	GPIOD->LCKR = (1 << 16) | (1 << 12);

	// 2. WR LCKR[16] = ‘0’ + LCKR[15:0]
	GPIOD->LCKR = (1 << 12);

	// 3. WR LCKR[16] = ‘1’ + LCKR[15:0]
	GPIOD->LCKR = (1 << 16)| (1 << 12);

	// 4. RD LCKR
	lock_status = GPIOD->LCKR;

	// 5. RD LCKR[16] = ‘1’
	lock_status = (GPIOD->LCKR & 0x010000) >> 16;

	while(1)
	{
		GPIOD->BSRR |= (1 << 12);
		delay(100);

		GPIOD->BSRR |= (1 << 28);
		delay(100);
	}
}
