/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stm32f407xx.h>

void delay(uint32_t t)
{
	for(int i=0;i<t;i++)
	{
		for(int j=0;j<1000;j++)
		{

		}
	}
}

void GPIO_Init(void)
{
	// Enable clock for port A and port D
	RCC->AHB1ENR |= (1 << 0) | (1 << 3);

	// Mode: Set PA0 as Input
	GPIOA->MODER &= ~(3U << 0);

	// No pull-up, pull-down(exist a resistor on board)
	GPIOA->PUPDR &= ~(3u<<0);

	// Mode: Set PD12 as output
	GPIOD->MODER &= ~(3U << 24);
	GPIOD->MODER |= (1U << 24);

	// Output type: push-pull
	GPIOD->OTYPER &= ~(1 << 12);

	// Speed: medium
	GPIOD->OSPEEDR &= ~(3 << 24);
	GPIOD->OSPEEDR |= (1 << 24);
}

void HSE_Clock_Init(void)
{

}

void LSE_Clock_Init(void)
{

}

void LSI_Clock_Init(void)
{

}

void PLL_HSE_Clock_Init(void)
{

}

void PLL_HSI_Clock_Init(void)
{

}

void Clock_Out_Init(void)
{

}

int main(void)
{
	GPIO_Init();

	//HSE_Clock_Init();
	//LSE_Clock_Init();
	//LSI_Clock_Init();
	//HSE_Clock_Init();
	//PLL_HSE_Clock_Init();
	//PLL_HSI_Clock_Init();

	Clock_Out_Init();

	while(1)
	{

	}
}
